-- Abdulrahman AI OS — مخطط Supabase (شغّله في SQL Editor مرة واحدة)
-- الجدول يحتفظ بنسخ كاملة من state.json خارج الخادم (نسخ احتياطي متين).
create table if not exists public.state_snapshots (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz not null default now(),
  schema        text        not null default 'state/1',
  state_version integer     not null default 0,
  reason        text        not null default 'manual',
  sha256        text        not null,
  byte_size     integer     not null,
  payload       jsonb       not null
);

create index if not exists state_snapshots_created_at_idx
  on public.state_snapshots (created_at desc);

-- RLS مفعّل وبلا أي سياسة: لا يقرأ ولا يكتب أحد بالمفتاح العام (anon/publishable).
-- المفتاح السري (service_role) يتجاوز RLS، وهو الوحيد المستخدم من الخادم.
alter table public.state_snapshots enable row level security;
revoke all on public.state_snapshots from anon, authenticated;

-- إن أردت لاحقًا لوحة قراءة بالمفتاح العام، أضف سياسة ضيّقة صريحة (مثال يبقى معطّلًا):
-- create policy "anon reads snapshot dates only" on public.state_snapshots
--   for select to anon using (false);

-- ============================================================================
-- استعلامات مراقبة (شغّلها في SQL Editor — للمفتاح السري فقط، الجدول محجوب عن العام)
-- ============================================================================
-- كم نسخة لديّ وحجمها؟
--   select count(*) as snapshots, pg_size_pretty(sum(byte_size)::bigint) as total
--   from public.state_snapshots;
-- أحدث 10 نسخ:
--   select id, created_at, state_version, byte_size, reason, left(sha256, 12) as sha
--   from public.state_snapshots order by created_at desc limit 10;
--
-- استعادة طارئة داخل قاعدة البيانات (بلا طرفية) — تُعيد الحالة بجانب النسخ:
--   select payload from public.state_snapshots order by created_at desc limit 1;
--
-- استخدم موصل النظام للاستعادة الآمنة (يتحقق من البصمة ويأخذ نسخة محلية أولًا):
--   python3 -m connectors.supabase_state restore --id N --apply
-- ============================================================================
